### ISSUE TITLE
Got error while initializing

### ISSUE THREAD

**Issue by psanghee** [blurblah/clien_bot#3]
After fresh installation of mongodb and RabittMQ and no source code modification, I got below error. 

I'm under impression that we need to initialize the mongodb before running it. 

Do you have any suggestion? 
Thanks in advance. 
Replying in Korean would be welcomed.! 

$ python3 -m crawler
Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'clien_bot'), 'crawl_info')
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/mywork/clien_bot/crawler/__main__.py", line 64, in <module>
    main()
  File "/home/ubuntu/mywork/clien_bot/crawler/__main__.py", line 36, in main
    job = Job(app)
  File "/home/ubuntu/mywork/clien_bot/crawler/services/job.py", line 17, in __init__
    self.board_name = crawl_info['name']
TypeError: 'NoneType' object is not subscriptable

**Comment by blurblah** [comment]
안녕하세요.
mongodb에 특정 db, collection, doc 이 있어야 합니다.
관련된 내용을 README에 추가하거나 해서 다시 comment 달아둘게요.

혹은 소스를 따라가보셔도 어떤 내용이 필요한지 확인해 보실 수 있습니다.

**Comment by blurblah** [comment]
README.md 파일에 내용 추가해두었습니다.
참고하시고 이상한 부분이 있거나 추가 설명같은게 필요하시면 알려주세요. :)
